version: '3.4'

services:
  seekq.identity:
    image: ${DOCKER_REGISTRY-}seekqidentity
    ports:
      - "32701:80"
    build:
      context: .
      dockerfile: SeekQ.Identity/Dockerfile
    environment:
      ASPNETCORE_ConnectionStrings__MSSQL: "Server=seekq.mssql,1433;Database=SeekQ.Identity;User Id=sa;Password=Password123"

      #Email settings
      ASPNETCORE_Email__Server: "192.168.0.104"
      ASPNETCORE_Email__Port: "25"
      ASPNETCORE_Email__SenderName: "SeekQ"
      ASPNETCORE_Email__SenderEmail: "info@seekq.com"

networks:
  default:
    external:
      name: SEEKQ_NETWORK